apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default # Change this if using a different namespace
type: Opaque
data:
  mongo-username: bWFya2Jvc2lyZQ== # Base64-encoded username
  mongo-password: MDlrdW1hbW90by4= # Base64-encoded password

